jobs:
  canary:
    name: canary / ${{matrix.package}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - run: npm install
      - run: npm run build
      - uses: actions/checkout@v4
        with:
          path: canary/${{matrix.package}}
          repository: ${{matrix.package}}
      - run: |
          npm install
          for package in $(ls ../../packages); do
            npx rimraf "node_modules/**/$package"
          done
          npm test
        working-directory: canary/${{matrix.package}}
    strategy:
      fail-fast: false
      matrix:
        package:
          - micromark/micromark-extension-directive
          - micromark/micromark-extension-gfm
          - micromark/micromark-extension-mdx
          - remarkjs/react-markdown
          - remarkjs/remark
          - syntax-tree/mdast-util-from-markdown
      max-parallel: 2
  main:
    name: ${{matrix.node}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v5
    strategy:
      matrix:
        node:
          - lts/hydrogen
          - node
        os:
          - ubuntu-latest
          - windows-latest
name: main
on:
  - pull_request
  - push
